//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMarket.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryAttribute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoryAttribute()
        {
            this.ItemAttributes = new HashSet<ItemAttribute>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }
        public int ValueType { get; set; }
        public Nullable<int> ListId { get; set; }
        public bool IsMandatory { get; set; }
        public bool IsEnabled { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual AttributeValueType AttributeValueType { get; set; }
        public virtual Category Category { get; set; }
        public virtual ListAttribute ListAttribute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemAttribute> ItemAttributes { get; set; }
    }
}
