//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMarket.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.Documents = new HashSet<Document>();
            this.ItemAttributes = new HashSet<ItemAttribute>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> SellerID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDateUtc { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int PictureCount { get; set; }
        public System.Guid CoverPhotoId { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public string ItemStatus { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Location Location { get; set; }
        public virtual Seller Seller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemAttribute> ItemAttributes { get; set; }
        public virtual ItemStatu ItemStatu { get; set; }
    }
}
