//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMarket.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineMarketEntities : DbContext
    {
        public OnlineMarketEntities()
            : base("name=OnlineMarketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AttributeValueType> AttributeValueTypes { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CategoryAttribute> CategoryAttributes { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<ListAttribute> ListAttributes { get; set; }
        public virtual DbSet<ListOption> ListOptions { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Seller> Sellers { get; set; }
        public virtual DbSet<ItemAttribute> ItemAttributes { get; set; }
        public virtual DbSet<ItemStatu> ItemStatus { get; set; }
    }
}
